export const reviewActionTypes = {
    GET_REVIEWS_START: 'GET_REVIEWS_START',
    GET_REVIEWS_SUCCESS: 'GET_REVIEWS_SUCCESS',
    GET_REVIEWS_FAILURE: 'GET_REVIEWS_FAILURE',
    ADD_REVIEW_START: 'ADD_REVIEW_START',
    ADD_REVIEW_SUCCESS: 'ADD_REVIEW_SUCCESS',
    ADD_REVIEW_FAILURE: 'ADD_REVIEW_FAILURE'
};

 